# User config
author: "Alec Levy"
tagline: "Certfied Jekyll Theme"
description: "I'm a Software Engineer studying at the University of California, Santa Cruz! I'm passionate about full stack web development and building useful products and tools. I'm currently working under Colleen Jospehson in the jLab at UCSC.  "
keywords: "Fullstack, Web Development, Software Engineer, UCSC, Computer Science, React, SQL"
email: "aleclevy3@gmail.com"
linkedin: "https://www.linkedin.com/in/alec-levy-479058283/"
twitter: "https://twitter.com/"
github: "https://github.com/aleclevy"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed